// Countries and dial codes used by the enquiry form's Country and Phone Code dropdowns.
// Add more entries below following the same { name, dialCode } pattern if a buyer's
// country is missing.

export const countries = [
  { name: "India", dialCode: "+91" },
  { name: "United Arab Emirates", dialCode: "+971" },
  { name: "Saudi Arabia", dialCode: "+966" },
  { name: "Oman", dialCode: "+968" },
  { name: "Qatar", dialCode: "+974" },
  { name: "Kuwait", dialCode: "+965" },
  { name: "Bahrain", dialCode: "+973" },
  { name: "Iraq", dialCode: "+964" },
  { name: "Jordan", dialCode: "+962" },
  { name: "Yemen", dialCode: "+967" },
  { name: "Lebanon", dialCode: "+961" },
  { name: "Israel", dialCode: "+972" },
  { name: "Turkey", dialCode: "+90" },
  { name: "Iran", dialCode: "+98" },
  { name: "Germany", dialCode: "+49" },
  { name: "Netherlands", dialCode: "+31" },
  { name: "United Kingdom", dialCode: "+44" },
  { name: "Poland", dialCode: "+48" },
  { name: "France", dialCode: "+33" },
  { name: "Italy", dialCode: "+39" },
  { name: "Spain", dialCode: "+34" },
  { name: "Belgium", dialCode: "+32" },
  { name: "Switzerland", dialCode: "+41" },
  { name: "Sweden", dialCode: "+46" },
  { name: "Russia", dialCode: "+7" },
  { name: "Nigeria", dialCode: "+234" },
  { name: "Kenya", dialCode: "+254" },
  { name: "South Africa", dialCode: "+27" },
  { name: "Egypt", dialCode: "+20" },
  { name: "Ghana", dialCode: "+233" },
  { name: "Tanzania", dialCode: "+255" },
  { name: "Ethiopia", dialCode: "+251" },
  { name: "Morocco", dialCode: "+212" },
  { name: "Algeria", dialCode: "+213" },
  { name: "Malaysia", dialCode: "+60" },
  { name: "Vietnam", dialCode: "+84" },
  { name: "Indonesia", dialCode: "+62" },
  { name: "Thailand", dialCode: "+66" },
  { name: "Singapore", dialCode: "+65" },
  { name: "Philippines", dialCode: "+63" },
  { name: "Bangladesh", dialCode: "+880" },
  { name: "Sri Lanka", dialCode: "+94" },
  { name: "Pakistan", dialCode: "+92" },
  { name: "Nepal", dialCode: "+977" },
  { name: "China", dialCode: "+86" },
  { name: "Japan", dialCode: "+81" },
  { name: "South Korea", dialCode: "+82" },
  { name: "Australia", dialCode: "+61" },
  { name: "New Zealand", dialCode: "+64" },
  { name: "United States", dialCode: "+1" },
  { name: "Canada", dialCode: "+1" },
  { name: "Brazil", dialCode: "+55" },
  { name: "Mexico", dialCode: "+52" },
  { name: "Argentina", dialCode: "+54" },
  { name: "Other", dialCode: "+" },
];